// src/app/layout.tsx
import type { Metadata } from "next";
import type { Viewport } from 'next';
import { Geist, Geist_Mono } from "next/font/google";
import { GitCommitVertical, User } from 'lucide-react';
import "./globals.css";
import "../styles/custom.css";
import { MainNavigation } from "@/components/nav/MainNavigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nicole Trieu",
  description: "Portfolio generated by create next app"
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased min-h-screen flex flex-col`}
      >
        <MainNavigation />
        <main className="flex-1 pb-20">{children}</main>
        <footer className="fixed bottom-0 left-0 right-0 bg-white dark:bg-gray-900 border-t border-gray-200 dark:border-gray-700 z-10">
          <div className="container mx-auto px-4 sm:px-8 md:px-32 lg:px-32 xl:px-[300px] flex gap-4 sm:gap-[24px] flex-wrap items-center justify-center py-4">
            <a
              className="flex items-center gap-1 text-sm sm:text-base text-neutral-600 transition-all hover:text-neutral-800 dark:hover:text-neutral-100"
              href="https://github.com/nbtrieu"
              target="_blank"
              rel="noopener noreferrer"
            >
              <GitCommitVertical className="w-4 h-4 sm:w-5 sm:h-5" />
              GitHub
            </a>
            <a
              className="flex items-center gap-1 text-sm text-neutral-600 transition-all hover:text-neutral-800 dark:hover:text-neutral-100"
              href="https://www.linkedin.com/in/nicole-nghi-trieu/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <User className="w-4 h-4 sm:w-5 sm:h-5" />
              LinkedIn
            </a>
          </div>
        </footer>
      </body>
    </html>
  );
}